### ISSUE TITLE
Titel im Contao Manager falsch

### ISSUE THREAD

**Issue by mlwebworker** [trilobit-gmbh/contao-constants-bundle#1]
Bei der Anzeige im Contao Manager ist m.E. der Titel falsch.
Es wird angezeigt: Contao 4 Socialmedia Bundle trilobit-gmbh/contao-constants-bundle
Sollte doch aber "Contao 4 Constants Bundle" sein

**Comment by trilobit-gmbh** [comment]
:-( Danke für die Meldung.

**Comment by trilobit-gmbh** [comment]
done
