### ISSUE TITLE
PHP 8 support?

### ISSUE THREAD

**Issue by Defcon0** [trilobit-gmbh/contao-constants-bundle#10]
Hello,

could you please add php 8 support? Since there aren't too much relevant BC breaks, it shouldn't be too much of a problem. I could also create a PR for that one.

What do you say?

Bye Defcon0

**Comment by koertho** [comment]
Something new on this topic?

**Comment by trilobit-gmbh** [comment]
Hello, unfortunately there is nothing new here. However, we have firmly planned the PHP8 topic; but unfortunately could not start with it yet.

https://www.trilobit.de/ffekten/jobs-und-ausbildung/php-entwickler-m-w-d.html

**Comment by Defcon0** [comment]
We moved some of our extensions to php 8 with zero problems so far since the breaking changes in php 8 are very little and rather exotic.

Are you interested in a PR after we've been checking this?

**Comment by Defcon0** [comment]
Since we need to integrate the module in upcoming projects and would like avoid forking it again: is it ok for you that we create a PR for you and that you merge it in a short period of time?

**Comment by trilobit-gmbh** [comment]
PR are welcome ;-)

**Comment by Defcon0** [comment]
Here's the PR :-)

https://github.com/trilobit-gmbh/contao-constants-bundle/pull/11

Thanks for merging!

**Comment by Defcon0** [comment]
Any progress on that one?

**Comment by trilobit-gmbh** [comment]
1.2.0

**Comment by trilobit-gmbh** [comment]
Thanks for pr!

**Comment by Defcon0** [comment]
Thanks! :-)
