### ISSUE TITLE
tinyMCE-Support?

### ISSUE THREAD

**Issue by Defcon0** [trilobit-gmbh/contao-constants-bundle#4]
Hello,

since https://github.com/terminal42/contao-inserttags is archived, we're looking for a replacement. This bundle seems to fulfill nearly all requirements.

Only one thing is missing which is the tinyMCE support. Is this planned/thinkable?

Thanks.

Bye Defcon0

**Comment by trilobit-gmbh** [comment]
Hello,

Thank you for the report ;-)

What exactly do you mean by TinyMCE support?
The insert tags can be used / entered anywhere. Do you mean a supplementary menu entry with the available tags?

Unfortunately no additions are planned at the moment.

But I can see how the TinyMCE configuration can be easily expanded to output a supplementary menu item with the available tags.

At the moment, however, we do not have a customer who needs a corresponding supplement and would also like to pay ;-(
A paid order or pull request would of course be nice (and can also accelerate implementation) - or a donation via https://www.trilobit.de/trilobits/constants-ein-contao-bundle.html

Best regards
Peter

**Comment by Defcon0** [comment]
I think I should've made it clearer ;-)

It would simply be cool if you can add new constants not in sourcecode only (which non-developers can't) but using a wysiwyg editor.

(As it was in terminal42/contao-inserttags)

**Comment by Defcon0** [comment]
OK, I just finished a little extension bundle for your constants bundle which fulfills what we needed.

https://github.com/heimrichhannot/contao-constants-extension-bundle

Do you think, it might be an option to create a PR so that this goes into the bundle?

**Comment by trilobit-gmbh** [comment]
All PR are welcome ;-). I then look at the changes and apply them if they fit.
We use semantic versioning. The new version will then be assigned accordingly ;-)
Thank you and greetings
Peter

**Comment by Defcon0** [comment]
Could you please look at the bundle beforehands (don't worry, it doesn't have too many changes)? I'd like to avoid creating a PR which then will not be merged ;-)

**Comment by Defcon0** [comment]
To make things easier for you: I could also create a little list with the changes and we discuss whether you see a chance for a merge for them.

**Comment by trilobit-gmbh** [comment]
> Could you please look at the bundle beforehands (don't worry, it doesn't have too many changes)

This is not the way of a PR ;-(

> I could also create a little list with the changes and we discuss whether you see a chance for a merge for them.

Make it so ;-)

**Comment by Defcon0** [comment]
> This is not the way of a PR ;-(

I understand, but time is a limited resource :-)

Here's was I fixed in my module and would like to have in this bundle:

- adds support for multiline constants (the field is already a mediumtext, why not make it multiline?)
- adds optional wysiwyg editor support (tinyMCE) -> in tl_constants we have a new field "useWysiwygEditor". If clicked, the page reloads and the value field gets rte support
- the "constants" section is moved from "trilobit" to "content" in the backend modules since it's content
- the value field gets `decodeEntities` and `allowHtml` so that we can have html constants like address in the site notice (impressum) -> maybe configurable via `config.yml`

That's it. What do you think?

**Comment by trilobit-gmbh** [comment]
I'll take a look at the jobs and I'm sure to take on some of them.

> I understand, but time is a limited resource :-)

Now it is probably my time that is "wasted" ...
Nevertheless, thanks for the preparatory work and information.

**Comment by Defcon0** [comment]
One moment ;-) I never said I won‘t create a PR. I just wanted to discuss beforehands, which changes you consider merging.

Just tell me the features you‘re ok with and I‘ll create the pr for these festures.

**Comment by trilobit-gmbh** [comment]
We (trilobit) would be happy about these points as PR ;-)

- adds support for multiline constants (the field is already a mediumtext, why not make it multiline?)
- adds optional wysiwyg editor support (tinyMCE) -> in tl_constants we have a new field "useWysiwygEditor". If clicked, the page reloads and the value field gets rte support


This point means a break in compatibility, as the default behavior is changed:

> the value field gets decodeEntities and allowHtml so that we can have html constants like address in the site notice (imprint) -> maybe configurable via config.yml

Adjusting the actual status via config would be OK


The constants should remain in the "trilobit" area. Yes, it is certainly "content"; However, this is a simple and low-threshold way for us to show that we exist (and thus offer the bundle "just like that" and free of charge via this "advertising" - since these publications are usually not financed by customers).
Agencies that are bothered by this have the possibility to change this via an individual config.php in the system. By default it should stay that way ;-)


Many thanks for the support! Sorry for the little swipe ;-)

**Comment by Defcon0** [comment]
OK, I created the PR :-)

I hope, it's ok for you guys ;-) Maybe someone could re-check the polish translations, I just did them with DeepL and re-checked with google translate.

**Comment by trilobit-gmbh** [comment]
Version 1.1.0 released
Thanks!
