### ISSUE TITLE
Uncaught ArgumentCountError: Too few arguments to function

### ISSUE THREAD

**Issue by trilobit-gmbh** [trilobit-gmbh/contao-constants-bundle#7]
Hallo - ich habe hier eine Installation 4.11.3 die mir beim Versuch eines Updates nun nicht mehr funktioniert. Ich versuche den Vorgang zu rekonstruieren
Update via trakked vorbereitet
Hinweis auf 1 Update trilobit/contao-constants-bundle
trakked konnte sich nicht verbinden » Hinweis ich solle die Verbindung herstellen
nun habe ich via CM weitergemacht
Reparatur oder Abgesicherter Modus
Reparatur hat nicht funktionert
abgesicherter Modus hatte ich versucht Caches zu löschen, und Composer Update durchzuführen: Fehlermeldung
Fatal error: Uncaught ArgumentCountError: Too few arguments to function Symfony\Component\Config\Definition\Builder\TreeBuilder::__construct(), 0 passed in /var/www/vhosts/domain/pfad/zur/installation/vendor/trilobit-gmbh/contao-constants-bundle/src/DependencyInjection/Configuration.php on line 24 and at least 1 expected in /var/www/vhosts/domain/pfad/zur/installation/vendor/symfony/config/Definition/Builder/TreeBuilder.php:26
Frontend, Backend sind nicht mehr erreichbar - enden in einem ERROR 500
trakked zeigt die Seite als Down an
Ich vermute die Fehlerquelle in der Erweiterung Contao-Constants ... aber wie könnte ich das nun reparieren?
Bitte um Hilfestellung

https://contao.slack.com/archives/CK4J0KNDB/p1623069503317000

**Comment by bezin** [comment]
Seit Symfony 5.0 muss `TreeBuilder` mit einem Namen für den Tree Root aufgerufen werden. [Dieser fehlt in der Configuration Klasse.](https://github.com/trilobit-gmbh/contao-constants-bundle/blob/master/src/DependencyInjection/Configuration.php#L24)

> Dropped support for constructing a TreeBuilder without passing root node information.
https://github.com/symfony/symfony/blob/5.3/UPGRADE-5.0.md

**Comment by rabauss** [comment]
If you want to be compatible with Symfony < 4.2 - see:
https://github.com/terminal42/contao-url-rewrite/blob/master/src/DependencyInjection/Configuration.php#L26-L31

**Comment by trilobit-gmbh** [comment]
New version available: 1.1.1
